bot:
  name: change_me
  token: change_me
spring:
  application:
    name: AngryBot
  datasource:
    url: jdbc:postgresql://localhost:5432/tg_bot_angry_bot
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true